#switching to Travis-CI container-based infrastructure
sudo: false

language: php

php:
    - 7.0
    - 7.1

env:
    - WP_VERSION=latest WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
